### ISSUE TITLE
Improve how the y-axis tick labels are formatted

### ISSUE THREAD

**Issue by pnavarrc** [covid-projections/act-now-packages#326]
In some cases, the format of the metric values doesn't work well for the y-axis. In the chart below, we have `0.1` and `0.2` twice `http://localhost:3000/us/washington-wa`

![Image](https://user-images.githubusercontent.com/114084/197631807-6ab0d945-1ee8-4cae-b292-9f68a3cd5f4f.png)

On the vaccination chart, we have the opposite problem - the number format doesn't need to have 1 decimal place on the y-axis, but it does in other places.

![Image](https://user-images.githubusercontent.com/114084/197632218-1078a861-8a96-4ea3-97e4-621152717fd1.png)

One option is to set the format of the y-axis automatically with better defaults, or maybe to add that information to the metric.

**Comment by mikelehen** [comment]
I feel like we need a straightforward way to let you "override" the metric definitions when using our metric-aware components in case you need to tweak things on a per-component basis.

Here's a brief proposal I dropped into slack and would be interested in discussing with the team:

---
I’d like to discuss this with the team when Pablo is back, but dropping it here for people to noodle on if they feel like it.

I think it might be nice if we made all of our metric-aware components accept “override” props that can override the default metric behavior, e.g. you could do:
```
<MetricLineChart … metric={MetricId.Foo} metricOverrides={{formatOptions: { minimumFractionDigits: 2 }}} />
```
in the case that you know that you want to make the chart show more digits, e.g. to fix something like https://github.com/covid-projections/act-now-packages/issues/326

Or if you needed to override the extended name in the compare table for space reasons maybe you’d do something like:
```
<MetricCompareTable metrics={[MetricId.Foo, MetricId.Bar]} metricOverrides={{[MetricId.Foo]: { extendedName: 'Shorter name'}}} />
```

Another option would be to have some way to generate tweaked metrics on-the-fly, like maybe:
```
const shorterMetric = metricCatalog.derivedMetric(MetricId.Foo, { extendedName: 'shorter name' });

return (
  <MetricCompareTable metrics={[shorterMetric, MetricId.Bar]} />
);
```
That would be nice because we wouldn’t have to change anything with our metric-aware components…  but it seems a bit less convenient / straightforward to use.

**Comment by faihegberg** [comment]
As discussed during standup, before fixing this issue, we suspected there's a bug preventing our chart axes component from displaying the y-axis tick values correctly. After further investigation, I don't think there's a bug but we just haven't defined `formatOptions` in our metric definitions 😅 I'll create a PR with some default formatting and attach it to this issue.
