### ISSUE TITLE
Investigate 'Javascript heap out of memory' error

### ISSUE THREAD

**Issue by chasulin** [covid-projections/act-now-packages#356]
[An error saying "Javascript heap out of memory"](https://github.com/covid-projections/act-now-packages/actions/runs/3371400883/jobs/5593571363) popped up in the [WorldMap component PR](https://github.com/covid-projections/act-now-packages/pull/350), and blocked the pr from building successfully (and deploying to firebase). The source of the error seems to be the generation of typedocs, and [a quick fix was just to disable typedocs](https://github.com/covid-projections/act-now-packages/pull/350/commits/5bf4d08d66c17b6290c13fb8ba0cd1e392ac9cce) (remove yarn generate-docs from the build script) for now, so as to not block merging the WorldMap.

Things we've tried so far: 
- Doubling the amount of allotted memory
- Upgrading typedocs

**Comment by mikelehen** [comment]
It looks like this is a known typedoc issue: https://github.com/TypeStrong/typedoc/issues/1606. They are working on it, with the last progress update 9 days ago.

**Comment by mikelehen** [comment]
I've found that if we generate docs directly from the package sources (`yarn typedoc packages/*/src/index.ts`) instead of using the "monorepo support" (`yarn typedoc --entryPointStrategy packages .` then it's a lot faster and uses less memory.  The downside is the overall structure of the docs make it look like a single package with `assert/src`, `metrics/src`, etc. instead of separate modules (@actnowcoalition/assert, @actnowcoalition/metrics, etc.).  This isn't ideal for our public facing docs, but I think is probably fine for right now.

One side benefit of this change is that it makes cross-linking classes across packages work, which is currently another Typedoc bug with monorepo support (https://github.com/TypeStrong/typedoc/issues/1835).

When https://github.com/TypeStrong/typedoc/issues/1606 is addressed, we can revisit this.
